name: Deploy app to Github Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .Net Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      
      - name: Publish the project
        run: dotnet publish MyWebsite/MyWebsite.csproj -c Release -o release --nologo
        
      - name: Change base-tag in index.html from / to repo name
        run: sed -i 's/<base href="\/" \/>/<base href="\/my-site\/" \/>/g' release/wwwroot/index.html
      
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Commit wwwroot to Github Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-page
          FOLDER: release/wwwroot
